[package]
name = "aoc-2024-12-01"
version = "0.1.0"
edition = "2024"

[build-dependencies]
cc = "1"

[dependencies]
ahash = "0.8"
glib-sys = { version = "0.20", optional = true }

[features]
default = ["glib"]
glib = ["glib-sys"]

[dev-dependencies]
criterion = "0.5"
rstest = "0.26"

[[bench]]
name = "aoc_bench"
harness = false
